### ISSUE TITLE
How long I need to wait until you will done this lab?

### ISSUE THREAD

**Issue by undeparg** [Ladzislaf/react-lab-07#1]
Maybe you will have time to do it by 15/04/2022? And one another question: why you doesn't create shared repository for all of yours react labs?

**Comment by Ladzislaf** [comment]
0) whoareyou
1) you will wait as long as i say
2) have a nice day dick
3) maybe
4) stick your finger in my ass
5) because. to have a deploy on each of them on gh-pages

**Comment by undeparg** [comment]
Okay, now I clearly understand the situation, so I will close this issue.
